# Generated by Django 2.2 on 2019-07-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_t_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_event',
            name='timeline',
            field=models.CharField(default='', max_length=10),
        ),
    ]
