# Generated by Django 2.2 on 2019-07-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190729_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_issue',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
