# Generated by Django 2.2 on 2019-07-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_t_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_subscribe',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
