# Generated by Django 2.2 on 2019-07-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190730_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_subscribe',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
