# Generated by Django 2.2 on 2019-08-13 10:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190730_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_issue',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
