# Generated by Django 2.2 on 2019-09-05 18:35

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_t_issue_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
