# Generated by Django 2.2.6 on 2019-11-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190905_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
