# Generated by Django 2.2.6 on 2019-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191110_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_issue',
            name='header',
            field=models.CharField(max_length=100),
        ),
    ]
