# Generated by Django 2.2.6 on 2019-11-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191114_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='t_video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='t_video',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
