# Generated by Django 2.2.10 on 2020-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191121_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_event',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='t_video',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
