# Generated by Django 2.2.10 on 2020-06-12 22:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200612_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_issue',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
